In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [ ]:
data = pd.read_csv('/content/hwc.csv')
data

,P_NAME,P_DETECTION,P_DISCOVERY_FACILITY,P_YEAR,P_UPDATE,P_MASS,P_MASS_ERROR_MIN,P_MASS_ERROR_MAX,P_MASS_LIMIT,P_MASS_ORIGIN,...,S_ABIO_ZONE,S_TIDAL_LOCK,P_HABZONE_OPT,P_HABZONE_CON,P_TYPE_TEMP,P_HABITABLE,P_ESI,S_CONSTELLATION,S_CONSTELLATION_ABR,S_CONSTELLATION_ENG
0,OGLE-2016-BLG-1227L b,Microlensing,OGLE,2020,2020-04-02,250.00000,-120.00000,413.00000,0,Mass,...,NaN,0.214133,0,0,NaN,0,NaN,Scorpius,Sco,Scorpion
1,Kepler-276 c,Transit,Kepler,2013,2018-09-25,16.60000,-3.60000,4.40000,0,Mass,...,2.097783,0.316980,0,0,Hot,0,0.272032,Cygnus,Cyg,Swan
2,Kepler-829 b,Transit,Kepler,2016,2019-04-16,5.10000,NaN,NaN,0,M-R relationship,...,1.756317,0.459559,0,0,Hot,0,0.254763,Lyra,Lyr,Lyre
3,K2-283 b,Transit,K2,2018,2019-09-05,12.20000,NaN,NaN,0,M-R relationship,...,0.568374,0.443760,0,0,Hot,0,0.193906,Pisces,Psc,Fishes
4,Kepler-477 b,Transit,Kepler,2016,2019-04-16,4.94000,NaN,NaN,0,M-R relationship,...,0.768502,0.386150,0,0,Hot,0,0.276721,Lyra,Lyr,Lyre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5594,HD 222155 b,Radial Velocity,Haute-Provence Observatory,2011,2023-06-12,581.62598,-82.63539,111.23994,0,Mass,...,1.893917,0.541322,0,0,Cold,0,0.178593,Andromeda,And,Andromeda
5595,HD 88986 b,Radial Velocity,Haute-Provence Observatory,2023,2023-12-04,17.20000,-3.80000,4.00000,0,Mass,...,2.520276,0.543834,0,0,Hot,0,0.379540,Leo Minor,LMi,Little Lion
5596,Kepler-30 b,Transit,Kepler,2012,2023-11-28,11.30000,-1.40000,1.40000,0,Mass,...,1.249824,0.400198,0,0,Hot,0,0.241771,Lyra,Lyr,Lyre
5597,HD 3167 d,Radial Velocity,Multiple Observatories,2017,2023-04-17,4.33000,-0.45000,0.45000,0,Msini,...,0.787469,0.475336,0,0,Hot,0,0.272975,Pisces,Psc,Fishes
5598,OGLE-2019-BLG-1180L b,Microlensing,OGLE,2023,2024-01-05,555.24623,-161.13900,167.49557,0,Mass,...,NaN,0.377983,0,0,NaN,0,NaN,Sagittarius,Sgr,Archer

In [ ]:
# df = data[['P_MASS','P_RADIUS','P_PERIOD','P_SEMI_MAJOR_AXIS','P_ECCENTRICITY','P_INCLINATION','P_TEMP_SURF','P_TEMP_EQUIL','P_GRAVITY','P_DENSITY','S_TEMPERATURE','S_LUMINOSITY','S_RADIUS','S_MASS','S_HZ_OPT_MIN','S_HZ_OPT_MAX','S_HZ_CON_MIN','S_HZ_CON_MAX','P_ESI']]

df = data[['P_RADIUS','P_PERIOD','P_SEMI_MAJOR_AXIS','P_ECCENTRICITY','P_INCLINATION','P_TEMP_EQUIL','S_TEMPERATURE','S_RADIUS','S_MASS','P_ESI']]
df

,P_RADIUS,P_PERIOD,P_SEMI_MAJOR_AXIS,P_ECCENTRICITY,P_INCLINATION,P_TEMP_EQUIL,S_TEMPERATURE,S_RADIUS,S_MASS,P_ESI
0,13.90,NaN,3.4000,NaN,NaN,NaN,NaN,NaN,0.10,NaN
1,2.90,31.884000,0.1994,0.000,86.920,541.98483,5779.0,1.03,1.10,0.272032
2,2.11,6.883376,0.0678,0.000,89.820,1001.11710,5698.0,0.97,0.98,0.254763
3,3.52,1.921036,0.0291,NaN,NaN,1104.46820,5060.0,0.82,0.89,0.193906
4,2.07,11.119907,0.0911,0.000,87.750,681.30334,5240.0,0.79,0.87,0.276721
...,...,...,...,...,...,...,...,...,...,...
5594,13.40,3999.000000,5.1400,0.160,68.000,150.37253,5701.0,1.85,1.21,0.178593
5595,2.49,146.050000,0.5800,0.240,89.900,417.87626,5861.0,1.54,1.25,0.379540
5596,3.90,29.334340,0.1800,0.042,90.179,523.80007,5498.0,0.95,0.99,0.241771
5597,1.92,8.411200,0.0763,0.120,NaN,788.76035,5261.0,0.88,0.84,0.272975
5598,13.50,NaN,5.1900,NaN,NaN,NaN,NaN,NaN,0.55,NaN

In [ ]:
# df.dropna(inplace=True)
# df.reset_index(drop=True,inplace=True)

'''by dropping off the null values the r2_score was 0.96 only
so we replace the NaNs by mean values'''

mean_values = df.mean()
df.fillna(mean_values,inplace=True)

/tmp/ipython-input-4-3913094442.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(mean_values,inplace=True)

In [ ]:
x = df.drop('P_ESI',axis=1).values
y = df['P_ESI'].values

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
pipeline1 = make_pipeline(StandardScaler(),RandomForestRegressor())
pipeline1.fit(x_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('randomforestregressor', RandomForestRegressor())])

In [ ]:
predictions1 = pipeline1.predict(x_test)
print('R2 Score = ',r2_score(y_test,predictions1))
print('Mean Squared Error = ',mean_squared_error(y_test,predictions1))

R2 Score =  0.9950821627009652
Mean Squared Error =  8.483416619304318e-05

In [ ]:
# features = ['P_MASS','P_RADIUS','P_PERIOD','P_SEMI_MAJOR_AXIS','P_ECCENTRICITY','P_INCLINATION','P_TEMP_SURF','P_TEMP_EQUIL','P_GRAVITY',
            # 'P_DENSITY','S_TEMPERATURE','S_LUMINOSITY','S_RADIUS','S_MASS','S_HZ_OPT_MIN','S_HZ_OPT_MAX','S_HZ_CON_MIN','S_HZ_CON_MAX']
features = ['P_RADIUS','P_PERIOD','P_SEMI_MAJOR_AXIS','P_ECCENTRICITY','P_INCLINATION','P_TEMP_EQUIL','S_TEMPERATURE','S_RADIUS','S_MASS']
regressor1 = pipeline1.named_steps['randomforestregressor']
importances = regressor1.feature_importances_
feature_importance_df = pd.DataFrame({'Feature': features, 'Importance': importances})
print(feature_importance_df)

             Feature  Importance
0           P_RADIUS    0.382039
1           P_PERIOD    0.001083
2  P_SEMI_MAJOR_AXIS    0.000706
3     P_ECCENTRICITY    0.001383
4      P_INCLINATION    0.000394
5       P_TEMP_EQUIL    0.613048
6      S_TEMPERATURE    0.000556
7           S_RADIUS    0.000387
8             S_MASS    0.000404

#KEPLER data analysis

In [ ]:
kepler_data = pd.read_csv('/content/kepler.csv')
kepler_data

,kepid,KOI Name,Kepler Name,koi_disposition,koi_pdisposition,koi_score,P_PERIOD,P_ECCENTRICITY,P_RADIUS,P_SEMI_MAJOR_AXIS,P_INCLINATION,P_TEMP_EQUIL,koi_model_snr,koi_tce_plnt_num,S_TEMPERATURE,S_RADIUS,S_MASS
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,9.488036,0.0,2.26,0.0853,89.66,793.0,35.8,1.0,5455.0,0.927,0.919
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,54.418383,0.0,2.83,0.2734,89.57,443.0,25.8,2.0,5455.0,0.927,0.919
2,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,19.899140,0.0,14.60,0.1419,88.96,638.0,76.3,1.0,5853.0,0.868,0.961
3,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,1.736952,0.0,33.46,0.0267,67.09,1395.0,505.6,1.0,5805.0,0.791,0.836
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,2.525592,0.0,2.75,0.0374,85.41,1406.0,40.9,1.0,6031.0,1.046,1.095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9559,10090151,K07985.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0.527699,0.0,29.35,0.0128,20.78,2088.0,453.3,1.0,5638.0,0.903,1.005
9560,10128825,K07986.01,NaN,CANDIDATE,CANDIDATE,0.497,1.739849,0.0,0.72,0.0290,89.42,1608.0,10.6,1.0,6119.0,1.031,1.075
9561,10147276,K07987.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.021,0.681402,0.0,1.07,0.0157,88.60,2218.0,12.3,1.0,6173.0,1.041,1.104
9562,10155286,K07988.01,NaN,CANDIDATE,CANDIDATE,0.092,333.486169,0.0,19.30,1.2233,89.98,557.0,14.0,1.0,4989.0,7.824,2.190
9563,10156110,K07989.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,4.856035,0.0,1.05,0.0606,89.36,1266.0,8.2,1.0,6469.0,1.193,1.260

In [ ]:
kepler_data = kepler_data[kepler_data['koi_disposition']=='CONFIRMED']
kepler_data.dropna(inplace=True)
kepler_data.reset_index(drop=True,inplace=True)
kepler_data

/tmp/ipython-input-12-2877198927.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kepler_data.dropna(inplace=True)

,kepid,KOI Name,Kepler Name,koi_disposition,koi_pdisposition,koi_score,P_PERIOD,P_ECCENTRICITY,P_RADIUS,P_SEMI_MAJOR_AXIS,P_INCLINATION,P_TEMP_EQUIL,koi_model_snr,koi_tce_plnt_num,S_TEMPERATURE,S_RADIUS,S_MASS
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,9.488036,0.0,2.26,0.0853,89.66,793.0,35.8,1.0,5455.0,0.927,0.919
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,54.418383,0.0,2.83,0.2734,89.57,443.0,25.8,2.0,5455.0,0.927,0.919
2,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,2.525592,0.0,2.75,0.0374,85.41,1406.0,40.9,1.0,6031.0,1.046,1.095
3,10872983,K00756.01,Kepler-228 d,CONFIRMED,CANDIDATE,1.000,11.094321,0.0,3.90,0.0992,88.11,835.0,66.5,1.0,6046.0,0.972,1.053
4,10872983,K00756.02,Kepler-228 c,CONFIRMED,CANDIDATE,1.000,4.134435,0.0,2.77,0.0514,83.72,1160.0,40.2,2.0,6046.0,0.972,1.053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2720,10843431,K07378.01,Kepler-1999 b,CONFIRMED,CANDIDATE,0.994,8.739676,0.0,3.29,0.0713,82.59,577.0,15.6,1.0,4406.0,0.628,0.632
2721,7350067,K06863.01,Kepler-1646 b,CONFIRMED,CANDIDATE,1.000,4.485592,0.0,0.95,0.0295,89.36,365.0,15.0,1.0,3236.0,0.193,0.169
2722,8311864,K07016.01,Kepler-452 b,CONFIRMED,CANDIDATE,0.771,384.847556,0.0,1.09,0.9940,89.99,220.0,12.3,1.0,5579.0,0.798,0.892
2723,7935997,K05447.02,Kepler-1629 b,CONFIRMED,CANDIDATE,0.000,3.875943,0.0,0.68,0.0485,89.89,1081.0,14.2,1.0,5713.0,0.893,1.010
2724,8873450,K07913.01,Kepler-1975 b,CONFIRMED,CANDIDATE,0.000,24.278380,0.0,2.03,0.1456,88.62,432.0,13.6,6.0,4450.0,0.707,0.698

In [ ]:
kepler = kepler_data[features]
kepler

,P_RADIUS,P_PERIOD,P_SEMI_MAJOR_AXIS,P_ECCENTRICITY,P_INCLINATION,P_TEMP_EQUIL,S_TEMPERATURE,S_RADIUS,S_MASS
0,2.26,9.488036,0.0853,0.0,89.66,793.0,5455.0,0.927,0.919
1,2.83,54.418383,0.2734,0.0,89.57,443.0,5455.0,0.927,0.919
2,2.75,2.525592,0.0374,0.0,85.41,1406.0,6031.0,1.046,1.095
3,3.90,11.094321,0.0992,0.0,88.11,835.0,6046.0,0.972,1.053
4,2.77,4.134435,0.0514,0.0,83.72,1160.0,6046.0,0.972,1.053
...,...,...,...,...,...,...,...,...,...
2720,3.29,8.739676,0.0713,0.0,82.59,577.0,4406.0,0.628,0.632
2721,0.95,4.485592,0.0295,0.0,89.36,365.0,3236.0,0.193,0.169
2722,1.09,384.847556,0.9940,0.0,89.99,220.0,5579.0,0.798,0.892
2723,0.68,3.875943,0.0485,0.0,89.89,1081.0,5713.0,0.893,1.010
2724,2.03,24.278380,0.1456,0.0,88.62,432.0,4450.0,0.707,0.698

In [ ]:
kepler_predictions = pipeline1.predict(kepler)
kepler_predictions = pd.Series(kepler_predictions)
kepler_predictions.sort_values(ascending=False,inplace=True)
kepler_predictions

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

2655    0.922824
2546    0.892083
2466    0.852161
1683    0.846040
2475    0.845212
          ...
317     0.042473
469     0.042174
2598    0.042023
1509    0.041806
2313    0.041767
Length: 2725, dtype: float64

In [ ]:
kepler_top_10 = kepler_predictions.head(10)
kepler_top_10 = kepler_data.iloc[kepler_top_10.index]
kepler_top_10['ESI'] = kepler_predictions
kepler_top_10.reset_index(drop=True,inplace=True)
kepler_top_10

/tmp/ipython-input-15-4072913465.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kepler_top_10['ESI'] = kepler_predictions

,kepid,KOI Name,Kepler Name,koi_disposition,koi_pdisposition,koi_score,P_PERIOD,P_ECCENTRICITY,P_RADIUS,P_SEMI_MAJOR_AXIS,P_INCLINATION,P_TEMP_EQUIL,koi_model_snr,koi_tce_plnt_num,S_TEMPERATURE,S_RADIUS,S_MASS,ESI
0,11497958,K01422.05,Kepler-296 e,CONFIRMED,CANDIDATE,0.984,34.142051,0.0,1.06,0.1510,89.93,248.0,13.3,4.0,3526.0,0.383,0.394,0.922824
1,8424002,K03497.01,Kepler-1512 b,CONFIRMED,CANDIDATE,1.000,20.359719,0.0,0.80,0.1025,88.31,276.0,26.8,1.0,3419.0,0.344,0.346,0.892083
2,4138008,K04742.01,Kepler-442 b,CONFIRMED,CANDIDATE,0.993,112.303136,0.0,1.30,0.3874,89.90,241.0,13.1,1.0,4401.0,0.595,0.613,0.852161
3,3642335,K03010.01,Kepler-1410 b,CONFIRMED,CANDIDATE,0.996,60.866097,0.0,1.39,0.2465,90.00,244.0,15.4,1.0,3808.0,0.522,0.539,0.846040
4,6497146,K03284.01,Kepler-438 b,CONFIRMED,CANDIDATE,1.000,35.233069,0.0,0.97,0.1729,89.89,288.0,14.5,1.0,3749.0,0.524,0.554,0.845212
5,8845205,K00463.01,Kepler-560 b,CONFIRMED,CANDIDATE,0.001,18.477627,0.0,1.55,0.0887,89.27,267.0,75.7,1.0,3395.0,0.283,0.271,0.844355
6,8311864,K07016.01,Kepler-452 b,CONFIRMED,CANDIDATE,0.771,384.847556,0.0,1.09,0.9940,89.99,220.0,12.3,1.0,5579.0,0.798,0.892,0.843138
7,11768142,K02626.01,Kepler-1652 b,CONFIRMED,CANDIDATE,0.999,38.097072,0.0,1.58,0.1667,88.02,242.0,17.0,1.0,3554.0,0.398,0.426,0.824768
8,6106282,K04087.01,Kepler-440 b,CONFIRMED,CANDIDATE,1.000,101.110701,0.0,1.61,0.3548,89.97,229.0,24.1,1.0,4133.0,0.561,0.578,0.817017
9,8890150,K02650.01,Kepler-395 c,CONFIRMED,CANDIDATE,0.985,34.989785,0.0,1.14,0.1691,89.97,292.0,11.5,1.0,3765.0,0.521,0.526,0.796907

#TESS data analysis

In [ ]:
tess_data = pd.read_csv('/content/TESS.csv')
tess_data.dropna(inplace=True)
tess_data.reset_index(drop=True,inplace=True)
tess_data

,P_NAME,HOST_NAME,DISCOVERY_METHOD,P_PERIOD,P_SEMI_MAJOR_AXIS,P_RADIUS,P_MASS,P_DENSITY,P_ECCENTRICITY,P_TEMP_EQUIL,P_INCLINATION,S_TEMPERATURE,S_RADIUS,S_MASS
0,55 Cnc e,55 Cnc,Radial Velocity,0.736544,0.01544,2.080,7.81000,4.78,0.061,1958.0,87.300,5234.0,0.94,0.91
1,AU Mic b,AU Mic,Transit,8.463000,0.06450,4.070,17.00000,1.40,0.000,593.0,89.500,3700.0,0.75,0.50
2,AU Mic c,AU Mic,Transit,18.859019,0.11010,3.240,13.60000,2.30,0.000,454.0,89.000,3700.0,0.75,0.50
3,BD+20 594 b,BD+20 594,Transit,41.685500,0.24100,2.230,16.30000,7.89,0.000,546.0,89.550,5766.0,0.93,0.96
4,BD-14 3065 b,BD-14 3065 A,Transit,4.288973,0.06560,21.590,3932.00000,2.15,0.066,2001.0,80.780,6935.0,2.35,1.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,XO-5 b,XO-5,Transit,4.187756,0.05150,12.780,378.20000,1.06,0.000,1230.0,86.800,5430.0,1.13,1.04
858,XO-6 b,XO-6,Transit,3.765001,0.08150,23.203,1398.45200,0.62,0.000,1577.0,86.000,6720.0,1.93,1.47
859,XO-7 b,XO-7,Transit,2.864142,0.04421,15.390,225.34147,0.34,0.038,1743.0,83.450,6250.0,1.48,1.41
860,pi Men c,HD 39091,Transit,6.267900,0.06839,2.042,4.82000,2.97,0.000,1170.0,87.456,6037.0,1.10,1.09
861,pi Men c,HD 39091,Transit,6.268340,0.06702,2.060,4.52000,2.82,0.000,1147.0,87.310,5870.0,1.10,1.02

In [ ]:
tess = tess_data[features]
tess

,P_RADIUS,P_PERIOD,P_SEMI_MAJOR_AXIS,P_ECCENTRICITY,P_INCLINATION,P_TEMP_EQUIL,S_TEMPERATURE,S_RADIUS,S_MASS
0,2.080,0.736544,0.01544,0.061,87.300,1958.0,5234.0,0.94,0.91
1,4.070,8.463000,0.06450,0.000,89.500,593.0,3700.0,0.75,0.50
2,3.240,18.859019,0.11010,0.000,89.000,454.0,3700.0,0.75,0.50
3,2.230,41.685500,0.24100,0.000,89.550,546.0,5766.0,0.93,0.96
4,21.590,4.288973,0.06560,0.066,80.780,2001.0,6935.0,2.35,1.41
...,...,...,...,...,...,...,...,...,...
857,12.780,4.187756,0.05150,0.000,86.800,1230.0,5430.0,1.13,1.04
858,23.203,3.765001,0.08150,0.000,86.000,1577.0,6720.0,1.93,1.47
859,15.390,2.864142,0.04421,0.038,83.450,1743.0,6250.0,1.48,1.41
860,2.042,6.267900,0.06839,0.000,87.456,1170.0,6037.0,1.10,1.09
861,2.060,6.268340,0.06702,0.000,87.310,1147.0,5870.0,1.10,1.02

In [ ]:
tess_predictions = pipeline1.predict(tess)
tess_predictions = pd.Series(tess_predictions)
tess_predictions.sort_values(ascending=False,inplace=True)
tess_predictions

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

723    0.892674
722    0.857618
475    0.850860
724    0.847545
478    0.786387
         ...
827    0.042708
829    0.042670
858    0.042604
256    0.042121
644    0.041811
Length: 862, dtype: float64

In [ ]:
tess_top_10 = tess_predictions.head(10)
tess_top_10 = tess_data.iloc[tess_top_10.index]
tess_top_10['ESI'] = tess_predictions
tess_top_10.reset_index(drop=True,inplace=True)
tess_top_10

/tmp/ipython-input-19-3603964393.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tess_top_10['ESI'] = tess_predictions

,P_NAME,HOST_NAME,DISCOVERY_METHOD,P_PERIOD,P_SEMI_MAJOR_AXIS,P_RADIUS,P_MASS,P_DENSITY,P_ECCENTRICITY,P_TEMP_EQUIL,P_INCLINATION,S_TEMPERATURE,S_RADIUS,S_MASS,ESI
0,TRAPPIST-1 e,TRAPPIST-1,Transit,6.099615,0.02817,0.918,0.62,4.4,0.085,251.0,89.860,2559.0,0.12,0.08,0.892674
1,TRAPPIST-1 d,TRAPPIST-1,Transit,4.049610,0.02144,0.772,0.41,4.9,0.070,288.0,89.750,2559.0,0.12,0.08,0.857618
2,LHS 1140 b,LHS 1140,Transit,24.737120,0.08750,1.430,6.65,12.5,0.290,230.0,89.912,3131.0,0.19,0.15,0.850860
3,TRAPPIST-1 f,TRAPPIST-1,Transit,9.206690,0.03710,1.045,0.68,3.3,0.063,219.0,89.680,2559.0,0.12,0.08,0.847545
4,LHS 1140 b,LHS 1140,Transit,24.736959,0.09360,1.727,6.98,7.5,0.060,235.0,89.890,3216.0,0.21,0.18,0.786387
5,LHS 1140 b,LHS 1140,Transit,24.737230,0.09460,1.730,5.60,5.9,0.043,226.0,89.860,3096.0,0.22,0.18,0.777649
6,Kepler-22 b,Kepler-22,Transit,289.863876,0.81200,2.100,9.10,5.2,0.720,279.0,89.764,5596.0,0.87,0.86,0.713737
7,K2-18 b,K2-18,Transit,32.939630,0.14300,2.380,7.96,3.3,0.430,235.0,89.579,3457.0,0.41,0.36,0.704132
8,Kepler-22 b,Kepler-22,Transit,289.862300,0.84900,2.380,36.00,14.7,0.000,262.0,89.764,5518.0,0.98,0.97,0.703897
9,K2-3 d,K2-3,Transit,44.556456,0.20970,1.620,1.60,2.1,0.097,312.0,89.788,3835.0,0.60,0.62,0.685549

# TOP 2 planets with highest ESI

* ###   Kepler-296 e (0.923897)
* ###   TRAPPIST-1 e (0.902568)

# SVR

In [ ]:
from sklearn.svm import SVR

In [ ]:
pipeline2 = make_pipeline(StandardScaler(),SVR())
pipeline2.fit(x_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()), ('svr', SVR())])

In [ ]:
predictions2 = pipeline2.predict(x_test)
print('R2 Score = ',r2_score(y_test,predictions2))
print('Mean Squared Error = ',mean_squared_error(y_test,predictions2))

R2 Score =  0.7286705456473124
Mean Squared Error =  0.004680514344820064

In [ ]:
kepler_predictions = pipeline2.predict(kepler)
kepler_predictions = pd.Series(kepler_predictions)
kepler_predictions.sort_values(ascending=False,inplace=True)
kepler_predictions

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

1891    0.759379
2324    0.748515
2656    0.728339
2448    0.727965
2394    0.716792
          ...
1897    0.057674
2267    0.057006
443     0.055200
798     0.053035
2234    0.045813
Length: 2725, dtype: float64

In [ ]:
kepler_top_10 = kepler_predictions.head(10)
kepler_top_10 = kepler_data.iloc[kepler_top_10.index]
kepler_top_10['ESI'] = kepler_predictions
kepler_top_10.reset_index(drop=True,inplace=True)
kepler_top_10

/tmp/ipython-input-25-4072913465.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kepler_top_10['ESI'] = kepler_predictions

,kepid,KOI Name,Kepler Name,koi_disposition,koi_pdisposition,koi_score,P_PERIOD,P_ECCENTRICITY,P_RADIUS,P_SEMI_MAJOR_AXIS,P_INCLINATION,P_TEMP_EQUIL,koi_model_snr,koi_tce_plnt_num,S_TEMPERATURE,S_RADIUS,S_MASS,ESI
0,6444896,K03138.02,Kepler-1649 c,CONFIRMED,FALSE POSITIVE,0.374,19.535255,0.0,0.53,0.0649,89.65,161.0,5.9,2.0,2703.0,0.118,0.096,0.759379
1,8120608,K00571.05,Kepler-186 f,CONFIRMED,CANDIDATE,0.677,129.945392,0.0,1.18,0.3855,89.36,177.0,13.1,5.0,3751.0,0.443,0.452,0.748515
2,6444896,K03138.01,Kepler-1649 b,CONFIRMED,CANDIDATE,1.000,8.689108,0.0,0.49,0.0378,89.95,211.0,9.6,1.0,2703.0,0.118,0.096,0.728339
3,11497958,K01422.04,Kepler-296 f,CONFIRMED,CANDIDATE,0.927,63.335472,0.0,1.18,0.2279,89.99,202.0,13.0,5.0,3526.0,0.383,0.394,0.727965
4,11284772,K04622.01,Kepler-441 b,CONFIRMED,CANDIDATE,0.975,207.247850,0.0,1.56,0.5697,89.95,189.0,13.2,1.0,4339.0,0.553,0.573,0.716792
5,8459663,K04356.01,Kepler-1593 b,CONFIRMED,CANDIDATE,0.976,174.510276,0.0,1.74,0.4836,89.99,186.0,14.8,1.0,4367.0,0.452,0.496,0.706782
6,9002278,K00701.04,Kepler-62 f,CONFIRMED,CANDIDATE,0.000,267.282521,0.0,1.43,0.7279,89.91,207.0,19.3,4.0,4926.0,0.662,0.727,0.703405
7,11497958,K01422.05,Kepler-296 e,CONFIRMED,CANDIDATE,0.984,34.142051,0.0,1.06,0.1510,89.93,248.0,13.3,4.0,3526.0,0.383,0.394,0.699551
8,4138008,K04742.01,Kepler-442 b,CONFIRMED,CANDIDATE,0.993,112.303136,0.0,1.30,0.3874,89.90,241.0,13.1,1.0,4401.0,0.595,0.613,0.692171
9,8311864,K07016.01,Kepler-452 b,CONFIRMED,CANDIDATE,0.771,384.847556,0.0,1.09,0.9940,89.99,220.0,12.3,1.0,5579.0,0.798,0.892,0.691498

In [ ]:
tess_predictions = pipeline2.predict(tess)
tess_predictions = pd.Series(tess_predictions)
tess_predictions.sort_values(ascending=False,inplace=True)
tess_predictions

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

725    0.701461
724    0.693441
723    0.681866
722    0.661827
476    0.659788
         ...
106   -0.036518
63    -0.039858
82    -0.039999
165   -0.042621
152   -0.045310
Length: 862, dtype: float64

In [ ]:
tess_top_10 = tess_predictions.head(10)
tess_top_10 = tess_data.iloc[tess_top_10.index]
tess_top_10['ESI'] = tess_predictions
tess_top_10.reset_index(drop=True,inplace=True)
tess_top_10

/tmp/ipython-input-27-3603964393.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tess_top_10['ESI'] = tess_predictions

,P_NAME,HOST_NAME,DISCOVERY_METHOD,P_PERIOD,P_SEMI_MAJOR_AXIS,P_RADIUS,P_MASS,P_DENSITY,P_ECCENTRICITY,P_TEMP_EQUIL,P_INCLINATION,S_TEMPERATURE,S_RADIUS,S_MASS,ESI
0,TRAPPIST-1 g,TRAPPIST-1,Transit,12.352940,0.04510,1.127,1.34,5.20,0.061,199.0,89.710,2559.0,0.12,0.08,0.701461
1,TRAPPIST-1 f,TRAPPIST-1,Transit,9.206690,0.03710,1.045,0.68,3.30,0.063,219.0,89.680,2559.0,0.12,0.08,0.693441
2,TRAPPIST-1 e,TRAPPIST-1,Transit,6.099615,0.02817,0.918,0.62,4.40,0.085,251.0,89.860,2559.0,0.12,0.08,0.681866
3,TRAPPIST-1 d,TRAPPIST-1,Transit,4.049610,0.02144,0.772,0.41,4.90,0.070,288.0,89.750,2559.0,0.12,0.08,0.661827
4,LHS 1140 b,LHS 1140,Transit,24.737230,0.09460,1.730,5.60,5.90,0.043,226.0,89.860,3096.0,0.22,0.18,0.659788
5,LHS 1140 b,LHS 1140,Transit,24.736959,0.09360,1.727,6.98,7.50,0.060,235.0,89.890,3216.0,0.21,0.18,0.656624
6,LHS 1140 b,LHS 1140,Transit,24.737120,0.08750,1.430,6.65,12.50,0.290,230.0,89.912,3131.0,0.19,0.15,0.653538
7,K2-3 d,K2-3,Transit,44.556456,0.20970,1.620,1.60,2.10,0.097,312.0,89.788,3835.0,0.60,0.62,0.610364
8,TRAPPIST-1 c,TRAPPIST-1,Transit,2.421823,0.01521,1.056,1.38,6.45,0.083,342.0,89.670,2559.0,0.12,0.08,0.604739
9,Kepler-138 d,Kepler-138,Transit,23.092300,0.12880,1.510,2.10,3.60,0.010,345.0,89.040,3841.0,0.54,0.54,0.589140